name: ðŸš€ Build fraglet-entrypoint

on:
  push:
    paths:
      - 'entrypoint/**'
  pull_request:
    paths:
      - 'entrypoint/**'
  workflow_dispatch:

jobs:
  build:
    name: ðŸ›  Build fraglet-entrypoint
    uses: ./.github/workflows/build-entrypoint-reusable.yml



